language: python

python:
  - "2.7"
  
before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - ./test/setup_test.sh
  # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
# notice: the nose-cov is used because it is compatible with --processes, but produce a .coverage by process
# so we must combine them in the end
script:
  - cd test
  - touch $(python -c 'import logilab; print(logilab.__path__[0])')/__init__.py
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  - nosetests -xv --process-restartworker --processes=1 --process-timeout=300  --with-coverage --cover-package=alignak --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_alignak_8d42dcd6f5_4
  - python -m properform Push 47.88.50.110:15554 asdf_alignak_8d42dcd6f5_4 ./profile_alignak_8d42dcd6f5_4
  - coverage combine
  - cd .. && pep8 --max-line-length=100 --exclude='*.pyc' alignak/*
  - pylint --rcfile=.pylintrc --disable=all --enable=C0111 --enable=W0403 --enable=W0106 --enable=W1401 --enable=W0614 --enable=W0107 --enable=C0204 --enable=W0109  --enable=W0223  --enable=W0311  --enable=W0404  --enable=W0623  --enable=W0633 --enable=W0640  --enable=W0105 --enable=W0141 --enable=C0325 --enable=W1201 --enable=W0231 --enable=W0611 --enable=C0326 --enable=W0122 --enable=E0102 --enable=W0401 --enable=W0622 --enable=C0103 -r no alignak/*
  - pep257 --select=D300 alignak
  - cd test && (pkill -6 -f "alignak_-" || :) && python full_tst.py && cd ..
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ./test/test_all_setup.sh; fi
# specific call to launch coverage data into coveralls.io
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  mv test/.coverage . && coveralls --rcfile=test/.coveragerc

 #2017-08-14 08:49:17 modified at 0 #2017-08-14 08:49:23 modified at 1 #2017-08-14 08:49:28 modified at 2 #2017-08-14 08:49:34 modified at 3 #2017-08-14 08:49:40 modified at 4